---
# tasks file for openvpn (Ubuntu specific)

- name: Install OpenVPN GPG key
  apt_key: >
    url=https://swupdate.openvpn.net/repos/repo-public.gpg
    state=present
  tags: openvpn

- name: Add OpenVPN repository
  apt_repository: >
    repo='deb http://swupdate.openvpn.net/apt trusty main'
    state=present
  tags: openvpn

- name: Install OpenVPN packages
  apt: name={{ item }} state=present update_cache=yes
  with_items: openvpn_packages
  tags: openvpn

- name: Create OpenVPN defaults configuration
  template: >
    src=openvpn.default.j2
    dest=/etc/default/openvpn
    owner=root
    group=root
    mode=0644
  notifies: restart openvpn
  tags: openvpn
